export const coimbatoreAreas = [
  "Gandhipuram",
  "RS Puram",
  "Peelamedu",
  "Singanallur",
  "Saibaba Colony",
  "Ukkadam",
  "Town Hall",
  "Ganapathy",
  "Ramanathapuram",
  "Hope College",
  "Saravanampatti",
  "Kovaipudur",
  "Sundarapuram",
  "Kuniyamuthur",
  "Podanur",
  "Perur",
  "Thudiyalur",
  "Kavundampalayam",
  "Vadavalli",
  "Marudamalai",
  "Kalapatti",
  "Neelambur",
  "Irugur",
  "Ondipudur",
  "Vilankurichi",
  "Race Course",
  "Puliyakulam",
  "Kurichi",
  "Madukkarai",
];